"""añade imagen al modelo post

Revision ID: 6829e952f416
Revises: a3c0022300c9
Create Date: 2020-08-08 20:24:56.042224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6829e952f416'
down_revision = 'a3c0022300c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'image_name')
    # ### end Alembic commands ###
